name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: ">=3.11"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: deps
        run: make dev INSTALL_EXTRA=lint

      - name: lint
        run: make lint

  all-lints-pass:
    if: always()

    needs:
    - lint

    runs-on: ubuntu-latest

    steps:
      - name: check lint jobs
        uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # v1.3.0
        with:
          jobs: ${{ toJSON(needs) }}
